# docker run -p 80:80 --link regserver:regserver -i -t dougbtv/bowline-nginx

# this doesn't quite play with my mindset so well... so, just a sketch to begin with.

nginx:
  build: nginx/.
  image: dougbtv/bowline-nginx
  ports:
   - "80:80"
  links:
   - regserver
regserver:
  image: registry
  ports:
   - "5000:5000"